### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by ericel** [gethinoakes/ngx-masonry#13]
Critical dependency: the request of a dependency is an expression
```
    "@angular/core": "^5.2.0",
   "ngx-masonry": "^1.0.1",
```

```
WARNING in ./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (D:\websites\website\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (D:\websites\website\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (D:\websites\website\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (D:\websites\website\node_modules\webpack\lib\Compiler.js:502:17)
    at D:\websites\website\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (D:\websites\website\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (D:\websites\website\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ngx-masonry/ngx-masonry.es5.js
 @ ./src/app/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```
  Still having this error.

**Comment by ghillert** [comment]
Hitting the exact same issue - Using Angular `5.2`, even for non-AOT dev builds:

```
WARNING in ./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
```

**Comment by renzo031109** [comment]
ghillert I have the same issue.

**Comment by ghillert** [comment]
Looks like updating the project dependency to Angular5 will fix the issue. Rebuilt `ngx-masonry` locally and it works for me.

**Comment by Taewa** [comment]
@ghillert 
I have tried what as you said.

I opened `package.json` of ngx-masonry, update to `5.2.0` anything related to Angular then `npm install` (Im using angular 5.2.0 in my project).
and then `npm run build`.
But no luck. I get following error.
```
ERROR in Error during template compile of 'NgxMasonryModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.
../@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

Can you explain how to rebuild?

**Comment by akatrukhin** [comment]
@Taewa Install plugin ngx-masonry, using terminal go to your node_modules/ngx-masonry and run the command npm install -g npm-check-updates, Then use the command ncu -u The following package should update to the latest version, If the packages are still pointing to Angular 4, try to install it manually. If you still have the issue, go to node_modules/ngx-masonry/node_modules/@angular/core and do the same commands there. After that, it should work perfectly.  Tested with: Angular 5.2.10, -prod and -aot also are working perfectly.

**Comment by Taewa** [comment]
@gbesset 
I actually forked one of the angular masonry and [have created my own](https://www.npmjs.com/package/ngx-isotopex).
