### ISSUE TITLE
Error when running command ionic cordova build ios --prod --aot

### ISSUE THREAD

**Issue by peluqui2010** [gethinoakes/ngx-masonry#16]
Can you help me, cause i have that error when i want to complile my project with --prod flag!!

Thanks

"typescript error
            Error during template compile of 'NgxMasonryModule' Function calls are not supported in decorators in
            'NgModule' 'NgModule' calls a function at @angular/core/core.ts(194,50).

Error: The Angular AoT build failed. See the issues above
    at /Users/martindesk/Desktop/Proyectos/UltimasPropiedadesIOS/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:237:55
    at step (/Users/martindesk/Desktop/Proyectos/UltimasPropiedadesIOS/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Users/martindesk/Desktop/Proyectos/UltimasPropiedadesIOS/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Users/martindesk/Desktop/Proyectos/UltimasPropiedadesIOS/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>"

**Comment by AstRonin** [comment]
The same error with --prod flug using angular_cli:

`ERROR in Error during template compile of 'NgxMasonryModule'
  Function calls are not supported in decorators in 'NgModule'
    'NgModule' calls a function at ..\@angular\core\core.ts(194,50).`

And with --dev flug I see follow error in browser console:

`Unexpected value 'NgxMasonryModule' imported by the module 'AppModule'. Please add a @NgModule annotation.`

My versions:
```Angular CLI: 1.7.3
Node: 7.10.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack: 3.11.0
```

**Comment by AhHa45** [comment]
I have the same issue
    "@angular/core": "^5.2.10",
